version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5454:5432

  nats:
    image: 'nats:0.8.0'
    networks:
      - nats
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
    network_mode: "nats"
