name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Dependencies 
      working-directory: jobs
      run: go mod download

    - name: Build
      working-directory: jobs
      run: go build -v ./...

    - name: Test
      working-directory: jobs
      run: go test -v ./...
